### ISSUE TITLE
App not found associated with it 

### ISSUE THREAD

**Issue by PrasadShete20** [EnjiRouz/Parking-Lot-Video-Object-Detection#1]
This file does not have an app associated with it for performing this action. Please install an app or if one installed , create an association in the default apps settings page            

This is the message I get when I run 
Where is the Parking lot app , I couldn't find it 
Plz help

**Comment by EnjiRouz** [comment]
> This file does not have an app associated with it for performing this action. Please install an app or if one installed , create an association in the default apps settings page
> 
> This is the message I get when I run
> Where is the Parking lot app , I couldn't find it
> Plz help

You don't have Python installed probably or you use wrong command to run main.py

**Comment by PrasadShete20** [comment]
yeah but later , i got this error 

Traceback (most recent call last):
  File "main.py", line 209, in <module>
    net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")  # или "yolov3.weights" и "yolov3-tiny.cfg"
cv2.error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\dnn\src\darknet\darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3.cfg in function 'cv::dnn::dnn4_v20181221::readNetFromDarknet'

**Comment by PrasadShete20** [comment]
Nd also I forgot to thank you 😅,
Thank you for your prompt response

**Comment by EnjiRouz** [comment]
> yeah but later , i got this error
> 
> Traceback (most recent call last):
> File "main.py", line 209, in
> net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg") # или "yolov3.weights" и "yolov3-tiny.cfg"
> cv2.error: OpenCV(4.0.1) C:\ci\opencv-suite_1573470242804\work\modules\dnn\src\darknet\darknet_importer.cpp:207: error: (-212:Parsing error) Failed to parse NetParameter file: yolov3.cfg in function 'cv::dnn::dnn4_v20181221::readNetFromDarknet'

You should install **OpenCV** first. I use **cv2** version 4.4.0 
And use "yolov3-tiny.cfg" and "yolov3-tiny.weights" in paths like this
`net = cv2.dnn.readNet("yolov3-tiny.weights", "yolov3-tiny.cfg")`

or download yolov3.weights and yolov3.cfg (or above) from [YOLO](https://github.com/AlexeyAB/darknet)

**Comment by PrasadShete20** [comment]
Tysm , app got created .What does
Debug screenshot in the repo refers to ? 
How to get those green border of car detection?

**Comment by EnjiRouz** [comment]
> Tysm , app got created .What does
> Debug screenshot in the repo refers to ?
> How to get those green border of car detection?

uncomment main.py line 189 and 204 to use debug drawing (one for chosen parking area and one for detected cars)
