### ISSUE TITLE
Why all the cars in the Parking zones are not being detected  and I also tried with the help of Debugger , what may be the issue?

### ISSUE THREAD

**Issue by PrasadShete20** [EnjiRouz/Parking-Lot-Video-Object-Detection#2]
![parklotcam4](https://user-images.githubusercontent.com/65165736/119233208-82692b00-bb45-11eb-87a8-31d27ce214f5.PNG)
![parklotcam9](https://user-images.githubusercontent.com/65165736/119233097-f7883080-bb44-11eb-8a5d-ee35d7f0895c.PNG)
![parklotcam11](https://user-images.githubusercontent.com/65165736/119233098-fb1bb780-bb44-11eb-9894-157a4c46181a.PNG)
![parklotcam12](https://user-images.githubusercontent.com/65165736/119233101-fe16a800-bb44-11eb-8ba5-f82b48014c46.PNG)

**Comment by EnjiRouz** [comment]
Maybe it's because cars images haven't been recognized at the required frame (computer makes calculations not fast enough)

1. Have you tried to download yolov3.weights and yolov3.cfg (or above, like yolo4) from [YOLO](https://github.com/AlexeyAB/darknet)?

2. Have you made any code changes?

**Comment by PrasadShete20** [comment]
I had used yolo3 tiny weights , yolo3 tiny .cfg and also I haven't made any changes in code

**Comment by EnjiRouz** [comment]
> I had used yolo3 tiny weights , yolo3 tiny .cfg and also I haven't made any changes in code

So, as I've told you before, try to download yolov3.weights and yolov3.cfg (or above, like yolo4) from [YOLO](https://github.com/AlexeyAB/darknet)

Maybe that would help. It could improve recognition quality a little bit. 

But, maybe your machine just not as fast as mine. So you've just had a recognition delay. Try to make checks every minute then
